routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('index');
Route::get('posts', 'HomeController@posts')->name('posts');

$dashboard_options = [
    'prefix' => 'dashboard',
    'as' => 'dashboard.',
    'namespace' => 'Dashboard',
    'middleware' => [
        'auth:web'
    ],
];

Route::group($dashboard_options, function () {
    Route::get('/', 'HomeController@index')->name('index');

    // Route::resource('admins', 'AdminController');
    Route::resource('posts', 'PostController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;

class Post extends Model
{
    /**
    * The attributes that are mass assignable.
    *
    * @var array
    */
    protected $fillable = [
        'title' ,'body' ,'image' ,'user_id'
    ];

    protected $appends = ['image_url'];

    /**
    * Upload destination for posts
    */
    public $upload_distination = '/uploads/images/posts/';

    /**
    * Accessors & Mutators
    */
    public function setImageAttribute($value)
    {
        if (!$value instanceof UploadedFile) {
            $this->attributes['image'] = $value; // for testing purposes when using faker
            return;
        }
        $image_name = str_random(60);
        $image_name = $image_name.'.'.$value->getClientOriginalExtension();
        $value->move(public_path($this->upload_distination),$image_name);
        $this->attributes['image'] = $image_name;
    }

    public function getImageUrlAttribute()
    {
        if ($this->image) {
            //check if it's a link or just an encoded name
            return strpos($this->image ,'http') !== FALSE ? $this->image : asset($this->upload_distination.$this->image);
        }
        return '';
    }

    /**
    * Relations
    */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\AdminCreateRequest;
use App\Http\Requests\Dashboard\AdminUpdateRequest;
use App\User;

class AdminController extends Controller
{
    protected $base_view_path = 'dashboard.admins.';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $index = request()->get('page', 1);
        $data['counter_offset'] = ($index * 20) - 20;
        $data['resources'] = User::orderBy('id', 'DESC')->paginate(20);
        $data['total_resources_count'] = User::count();
        return view($this->base_view_path . 'index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->base_view_path . 'create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminCreateRequest $request)
    {
        $data = $request->all();

        $data['password'] = bcrypt($data['password']);
        $user = User::create($data);

        alert()->success('Admin created successfully.', 'Success');
        return redirect()->route('dashboard.admins.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $admin)
    {
        $data['resource'] = $admin;
        return view($this->base_view_path . 'show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $admin)
    {
        $data['resource'] = $admin;
        return view($this->base_view_path . 'edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminUpdateRequest $request, User $admin)
    {
        $data = $request->all();

        if ($request->has('password') && !$data['password']) {
            unset($data['password']);
        }elseif ($request->has('password')) {
            $data['password'] = bcrypt($data['password']);
        }
        $admin->update($data);

        alert()->success('Admin updated successfully.', 'Success');
        return redirect()->route('dashboard.admins.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $admin)
    {
        $admin->delete();
        return response()->json([
            'statusCode' => 200,
            'message' => 'Admin deleted successfully.',
        ],200);
        // alert()->success('Admin deleted successfully.', 'Success');
        // return redirect()->route('dashboard.admins.index');
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        return view('dashboard.blank');
    }
}

app/Http/Controllers/Dashboard/PostController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\PostCreateRequest;
use App\Http\Requests\Dashboard\PostUpdateRequest;
use App\Events\PostCreateEvent;
use App\Post;

class PostController extends Controller
{
    protected $base_view_path = 'dashboard.posts.';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $index = request()->get('page', 1);
        $data['counter_offset'] = ($index * 20) - 20;
        $data['resources'] = Post::orderBy('id', 'DESC')->paginate(20);
        $data['total_resources_count'] = Post::count();
        return view($this->base_view_path . 'index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->base_view_path . 'create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostCreateRequest $request)
    {
        $data = $request->all();

        $post = Post::create($data);
        event(new PostCreateEvent($post));

        alert()->success('Post created successfully.', 'Success');
        return redirect()->route('dashboard.posts.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $data['resource'] = $post;
        return view($this->base_view_path . 'show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $data['resource'] = $post;
        return view($this->base_view_path . 'edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostUpdateRequest $request, Post $post)
    {
        $data = $request->all();

        if ($request->has('image')) {
            $file_path = public_path($post->upload_distination.$post->image);
            if ($post->image && file_exists($file_path)) {
                unlink($file_path);
            }
        }
        $post->update($data);

        alert()->success('Post updated successfully.', 'Success');
        return redirect()->route('dashboard.posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $file_path = public_path($post->upload_distination.$post->image);
        if ($post->image && file_exists($file_path)) {
            unlink($file_path);
        }
        $post->delete();
        return response()->json([
            'statusCode' => 200,
            'message' => 'Post deleted successfully.',
        ],200);
    }
}

resources/views/dashboard/posts/create.blade.php
@extends('layouts.dashboard.app')

@section('section-title')
<div class="row">
    <div class="col-md-4 col-sm-12">
        <h3 class="section-title">Create new post</h3>
    </div>
</div>
@stop

@section('content')
{{ Form::open(['route' => 'dashboard.posts.store' ,'files' => true]) }}
<div class="row">
    <div class="col-md-12">
        <h3 class="secondry-title">Post Info.</h3>
    </div>
    <div class="col-md-12">
        <div class="form-group margin-bottom20 col-md-6">
            <label class="control-label" for="image" style="width:100%;">
                <span class="text-danger">*</span>
                Image
            </label>
            <div class="col-md-6">
                <label for="image" style="width:100%;">
                    <img src="{{ asset('panel-assets/images/profile-picutre/01_img.png') }}" alt="Upload image" class="thumbnail" style="width:100%;cursor: pointer; cursor: hand;">
                    <input type="file" id='image' name='image' style="display:none;" onchange="preview(this)";>
                </label>
                <p class="text-danger" style="margin-bottom: 0;">{{ $errors->first('image') }}</p>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group margin-bottom20 col-md-12">
            <label class="control-label" for="title">
                <span class="text-danger">*</span>
                Title
            </label>
            {{ Form::text('title',old('title'),['id'=>'title','max' => 255 ,'required'=>'required','class' => 'form-control']) }}
            <p class="text-danger" style="margin-bottom: 0;">{{ $errors->first('title') }}</p>
        </div>
        <div class="form-group margin-bottom20 col-md-12">
            <label class="control-label" for="body">
                <span class="text-danger">*</span>
                Body
            </label>
            {{ Form::textarea('body',old('body'),['id'=>'body','required'=>'required','class' => 'form-control']) }}
            <p class="text-danger" style="margin-bottom: 0;">{{ $errors->first('body') }}</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-1 col-xs-4">
        <button type="submit" class="btn primary-btn">
            Save
        </button>
    </div>
    <div class="col-md-1 col-xs-4">
        <button type="reset" class="btn cancel-btn">
            Reset
        </button>
    </div>
</div>
{{ Form::close() }}
@stop

@section('scripts')
<script type="text/javascript">
function preview(input)
{
    var parent = $(input).parent();
    var preview = parent.find('img');
    var file    = input.files[0];
    var reader  = new FileReader();

    reader.addEventListener("load", function () {
        preview.attr('src',reader.result);
    }, false);

    if (file) {
        reader.readAsDataURL(file);
    }
}
</script>
@stop

resources/views/dashboard/posts/edit.blade.php
@extends('layouts.dashboard.app')

@section('section-title')
<div class="row">
    <div class="col-md-4 col-sm-12">
        <h3 class="section-title">Edit post</h3>
    </div>
</div>
@stop

@section('content')
{{ Form::open(['route' => ['dashboard.posts.update' ,$resource->id] ,'method' => 'PATCH' ,'files' => true]) }}
<div class="row">
    <div class="col-md-12">
        <h3 class="secondry-title">Post Info.</h3>
    </div>
    <div class="col-md-12">
        <div class="form-group margin-bottom20 col-md-6">
            <label class="control-label" for="image" style="width:100%;">
                <span class="text-danger">*</span>
                Image
            </label>
            <div class="col-md-6">
                <label for="image" style="width:100%;">
                    <img src="{{ $resource->image ? $resource->image_url : asset('panel-assets/images/profile-picutre/01_img.png') }}" alt="Upload image" class="thumbnail" style="width:100%;cursor: pointer; cursor: hand;">
                    <input type="file" id='image' name='image' style="display:none;" onchange="preview(this)";>
                </label>
                <p class="text-danger" style="margin-bottom: 0;">{{ $errors->first('image') }}</p>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group margin-bottom20 col-md-12">
            <label class="control-label" for="title">
                <span class="text-danger">*</span>
                Title
            </label>
            {{ Form::text('title',$resource->title,['id'=>'title','max' => 255 ,'required'=>'required','class' => 'form-control']) }}
            <p class="text-danger" style="margin-bottom: 0;">{{ $errors->first('title') }}</p>
        </div>
        <div class="form-group margin-bottom20 col-md-12">
            <label class="control-label" for="body">
                <span class="text-danger">*</span>
                Body
            </label>
            {{ Form::textarea('body',$resource->body,['id'=>'body','required'=>'required','class' => 'form-control']) }}
            <p class="text-danger" style="margin-bottom: 0;">{{ $errors->first('body') }}</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-1 col-xs-4">
        <button type="submit" class="btn primary-btn">
            Save
        </button>
    </div>
    <div class="col-md-1 col-xs-4">
        <button type="reset" class="btn cancel-btn">
            Reset
        </button>
    </div>
</div>
{{ Form::close() }}
@stop

@section('scripts')
<script type="text/javascript">
function preview(input)
{
    var parent = $(input).parent();
    var preview = parent.find('img');
    var file    = input.files[0];
    var reader  = new FileReader();

    reader.addEventListener("load", function () {
        preview.attr('src',reader.result);
    }, false);

    if (file) {
        reader.readAsDataURL(file);
    }
}
</script>
@stop

resources/views/dashboard/posts/index.blade.php
@extends('layouts.dashboard.app')

@section('stylesheets')
<style>
body {
    background-color:#edeff9;
}
</style>
@stop

@section('section-title')
<div class="row">
    <div class="col-md-4 col-xs-12">
        <h3 class="section-title contacts-section-title">
            Posts
        </h3>
    </div>
    <div class="col-md-8 col-md-offset-4 text-right col-xs-11">
        <!-- <a href="{ route('dashboard.posts.download' ,'csv') }}"class="btn btn-blue margin-left-10">
            To excel
        </a> -->
        <!-- <a href="{ route('dashboard.posts.download' ,'pdf') }}"class="btn btn-blue margin-left-10">
            To PDF
        </a> -->
        <a href="{{ route('dashboard.posts.create') }}"class="btn btn-blue margin-left-10">
            <span>+ </span>Create post
        </a>
    </div>
</div>
@stop

@section('content')
<div class="row">
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-5 margin-bottom10 margin-top20">
                <div class="total-customer-col pad5 pad-bottom5 col-md-12">
                    <div class="col-md-9 customer-stat-col-pad">
                        <h5 class="customer-stat-text pad5">Posts count</h5>
                    </div>
                    <div class="col-md-3 text-center">
                        <h5 class="customer-stat-num pad5">
                            {{ $total_resources_count }}
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row margin-top15">
    <div class="col-md-12">
        <div class="row margin-bottom10">
            {{ $resources->links() }}
        </div>
        <div class="row margin-bottom10 contacts-list-view-card pad15">
            <table class="table table-borderless table-responsive" style="margin-bottom:0;">
                <tbody>
                    <tr>
                        <th class="text-center" style="width:5%;">#</th>
                        <th style="width:20%;">
                            Image
                        </th>
                        <th style="width:20%;">
                            Title
                        </th>
                        <th style="width:50%;">
                            Body
                        </th>
                        <th></th>
                    </tr>
                    @foreach($resources as $resource)
                    <tr class="">
                        <td class="text-center">
                            <h3 class="contact-list-view-column-categ margin-top10 contact-details-view" style="font-weight: 400;">
                                {{ $counter_offset + $loop->iteration }}
                            </h3>
                        </td>
                        <td>
                            <img src="{{ $resource->image_url }}" alt="Not found" class="thumbnail" style="width:100%;">
                        </td>
                        <td>
                            <h3 class="contact-list-view-column-categ margin-top10 contact-details-view" style="font-weight: 400;">
                                <a href="{{ route('dashboard.posts.show', $resource->id) }}">
                                    {{ $resource->title }}
                                </a>
                            </h3>
                        </td>
                        <td>
                            <h3 class="margin-top10 contact-details-view" style="font-weight: 400;">
                                {{ $resource->body }}
                            </h3>
                        </td>
                        <td>
                            <div class="no-shadow btn-group pull-right" style="margin:0;padding:0;">
                                <button type="button" class="btn btn-sm edit-btn text-center margin-left-10 dropdown-toggle contact-edit-dots-shdw pad0" data-toggle="dropdown">
                                    <i class="fa fa-ellipsis-h fa-lg edit-btn-contact-ico-color"></i>
                                </button>
                                <ul class="dropdown-menu contact-dropdown pull-right">
                                    <li>
                                        <a href="{{ route('dashboard.posts.edit', $resource->id) }}">
                                            Edit
                                        </a>
                                    </li>
                                    <li>
                                        {{ Form::open(['route' => ['dashboard.posts.destroy' ,$resource->id] ,'method' => 'DELETE' ,'class' => 'delete-form']) }}
                                        <button type="submit">
                                            Delete
                                        </button>
                                        {{ Form::close() }}
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@stop
@section('scripts')
<script>
$(document).ready(function(){
    $('.delete-form').submit(function(e){
        e.preventDefault();
        var form = $(this);
        var url = $(this).attr('action');
        $.ajax({
            url: url,
            method: 'POST',
            data: form.serialize(),
            dataType: 'json',
            success: function(response){
                form.parents('tr').remove();
                swal({
                    title: "Success",
                    text: response.message,
                    type: "success"
                });
            }
        });
    });
});
</script>
@stop

resources/views/dashboard/posts/show.blade.php
@extends('layouts.dashboard.app')

@section('stylesheets')
<style>
body {
    background-color:#edeff9;
}
</style>
@stop

@section('section-title')
<div class="row">
    <div class="col-md-4 col-xs-12">
        <h3 class="section-title contacts-section-title">
            Post Info.
        </h3>
    </div>
    <div class="col-xs-12 col-md-3">
        <div class="row">
            <div class="col-md-4 sort-col col-xs-4">
            </div>
            <div class="col-md-3 contact-edit-col col-xs-4">
            </div>
        </div>
    </div>
    <div class="col-md-4 col-md-offset-1 text-right col-xs-11">
        <a href="{{ route('dashboard.posts.create') }}"class="btn btn-primary margin-left-10">
            <span>+ </span>Add post
        </a>
        <a href="{{ route('dashboard.posts.edit',$resource->id) }}"class="btn btn-warning margin-left-10">
            Edit post
        </a>
    </div>
</div>
@stop

@section('content')
<div class="row margin-top15">
    <div class="col-md-12">
        <div class="row margin-bottom10 contacts-list-view-card pad15">
            <table class="table table-borderless table-responsive" style="">
                <tbody>
                    <tr>
                        <th class="text-center" style="width:100px;">
                            ID
                        </th>
                        <td>
                            {{ $resource->id }}
                        </td>
                    </tr>
                    <tr>
                        <th class="text-center" style="width:100px;">
                            Title
                        </th>
                        <td>
                            @if($resource->image)
                            <img src="{{ $resource->image_url }}" alt="Upload image" class="thumbnail" style="width:100%;">
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th class="text-center" style="width:100px;">
                            Title
                        </th>
                        <td>
                            {{ $resource->title }}
                        </td>
                    </tr>
                    <tr>
                        <th class="text-center" style="width:100px;">
                            Body
                        </th>
                        <td>
                            {{ $resource->body }}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
@stop